name: 'Babilema'
description: 'A GitHub Action to turn issues into blog posts'
author: 'Arthur Wallendorff'
inputs:
  config:
    description: 'The path to the configuration file'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  color: 'blue'
  icon: 'edit'
