name: Generate blog

on:
  pull_request:
    branches: [ blog ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-blog:
    runs-on: ubuntu-latest

    steps:
    - name: 'Check out code'
      uses: actions/checkout@v4

    - name: 'Generate blog' 
      uses: ByteBakersCo/babilema-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        github_context: ${{ toJson(github) }}
