name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: docker build . --file Dockerfile --tag babilema

    - name: Run tests
      run: docker run --rm --entrypoint go babilema test ./...

    - name: Run program
      run: docker run --rm -e GITHUB_REPOSITORY=${{ github.repository }} -e GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} babilema
