name: Generate blog

on:
  pull_request:
    branches: [ blog ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 'Check out code'
      uses: actions/checkout@v2

    - name: 'Generate blog' 
      uses: ByteBakersCo/babilema-action@v1
